name: CICD Demo(terraform plan)

on:
  pull_request:
    branches:
      - main

env:
  AWS_ASSUME_ROLE: ${{ secrets.ASSUMEROLE_20240622 }}

permissions: write-all

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-1
        role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
        role-session-name: GitHubActions
        role-duration-seconds: 1200

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Plan
      id: plan
      working-directory: terraform
      run: |
        terraform plan -no-color > plan.txt
        cat plan.txt

    - name: 'Post Plan to PR'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const planResult = fs.readFileSync('./terraform/plan.txt', 'utf8');
          const planOutput = `## Terraform Plan Output\n\n\`\`\`terraform\n${planResult}\n\`\`\``;
          await github.rest.issues.createComment({
            ...context.repo,
            issue_number: context.issue.number,
            body: `Terraform Plan Result:\n\n${planOutput}`
          });
